### ISSUE TITLE
コードブロックの文字数

### ISSUE THREAD

**Issue by drillan** [drillan/sd202009#2]
いくつかのコードで途中で折り返されているものがありました。
@ymsk-p コードブロックで折り返されない上限の文字数がわかりましたら教えていただけますか？
予めコード1行当たりの文字数の上限がわかれば、整形ツールで読みやすいように整形できます。

**Comment by ymsk-p** [comment]
半角文字49字が最大になります。
全角文字が入る場合は2文字想定でお願いします。

**Comment by drillan** [comment]
承知しました
整形したコードはPDFのコメントに貼り付けます
もし、読みにくい場合にはソースを更新しますので、そちらを参照ください

**Comment by drillan** [comment]
> 整形したコードはPDFのコメントに貼り付けます

スイマセン、PDFにコメントした場合は最初のスペース(インデント)が除外されてしまうため、ソースコードのリンクをコメントに記入します

**Comment by ymsk-p** [comment]
わかりました！
